# Copyright (C) 2023 Toitware ApS. All rights reserved.

name: CI

on:
  workflow_dispatch:
    inputs:
      sign_macos:
        description: Sign the macOS binary
        type: boolean
        required: true
        default: false
      sign_windows:
        description: Sign the Windows binary
        type: boolean
        required: true
        default: false
  release:
    types: [published]
  push:
    branches:
      - "*"
      - "*/*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Hello
        shell: bash
        run: |
          echo "hello - ${{github.event_name}}"

      - name: Releasing
        if: github.event_name == 'release' && runner.os == 'Linux'
        shell: bash
        run: |
          echo "Releasing - ${{github.event.release.tag_name}}"
